# Generated by Django 5.0.1 on 2024-01-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeinfo',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='placeinfo',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='placeinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
