# Generated by Django 5.0.1 on 2024-01-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0005_alter_placeinfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeinfo',
            name='activity',
        ),
        migrations.AddField(
            model_name='placeinfo',
            name='readable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='placeinfo',
            name='workable',
            field=models.BooleanField(default=False),
        ),
    ]
