# Generated by Django 5.0.1 on 2024-02-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0007_placeinfo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeinfo',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
