# Generated by Django 4.2.7 on 2024-02-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0008_alter_placeinfo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeinfo',
            name='lat',
            field=models.FloatField(blank=True, default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placeinfo',
            name='lng',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
