# Generated by Django 4.2.7 on 2024-02-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0009_placeinfo_lat_placeinfo_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeinfo',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='placeinfo',
            name='lng',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
